title: Raghav Pant
description: CSEM masters student, Oden Institute, UT Austin
logo: '/images/headshot_small.png'
author: Raghav Pant
author_email: raghav.pant@utexas.edu
google_analytics: G-P4J6TKM133
theme: jekyll-theme-minimal
